#!/usr/bin/env bash

rm ~/.tmux.conf
rm ~/.tmux.conf.local
# link wholesale
for f in `find . -regex ".*/.tmux.conf.*"`; do
    echo ~/dotfiles/awesome-streamerrc/adrian/$f
    ln -s ~/dotfiles/awesome-streamerrc/adrian/$f ~/$f
done

